# Generated by Django 4.1.4 on 2023-05-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroesClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus_name', models.CharField(max_length=200)),
                ('eng_name', models.CharField(max_length=200)),
                ('adons_name', models.CharField(max_length=200)),
            ],
        ),
    ]
