# Generated by Django 4.1.4 on 2023-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_wiki', '0002_heroesclass_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroesclass',
            name='bg_image',
            field=models.ImageField(default='', upload_to='dnd_wiki/icons'),
        ),
    ]
