# Generated by Django 4.1.4 on 2023-05-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_wiki', '0003_alter_heroesclass_bg_image'),
    ]

    operations = [

        migrations.AddField(
            model_name='heroesclass',
            name='creations',
            field=models.TextField(default='default title'),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='deep_lore',
            field=models.TextField(blank=True, default='default title', null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='description_info1',
            field=models.TextField(blank=True, default='default title', null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='description_info2',
            field=models.TextField(blank=True, default='default title', null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='description_title1',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='description_title2',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='fast_creations',
            field=models.TextField(blank=True, default='default title', null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='lore_info',
            field=models.TextField(blank=True, default='default title', null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='name',
            field=models.CharField(default='default title', max_length=200),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='short_info',
            field=models.CharField(default='default title', max_length=200),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='source',
            field=models.CharField(default='default title', max_length=200),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='table',
            field=models.TextField(blank=True, default='default title', null=True),
        ),
        migrations.AlterField(
            model_name='heroesclass',
            name='bg_image',
            field=models.ImageField(blank=True, default='', upload_to='dnd_wiki/icons'),
        ),
    ]
