# Generated by Django 4.1.4 on 2023-05-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_wiki', '0004_classhomebrew_companions_heroesclass_creations_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='heroesclass',
            name='deep_lore',
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='class_ability_armor',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='class_ability_desc',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='class_ability_equipment1',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='class_ability_equipment2',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='class_ability_equipment3',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='class_ability_hp',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='class_ability_hp_1lvl',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='class_ability_hp_nextlvl',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='class_ability_safedice',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='class_ability_tools',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='class_ability_weapon',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='deep_lore_ability',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='deep_lore_decs',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='deep_lore_min_char',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroesclass',
            name='deep_lore_use',
            field=models.CharField(blank=True, default='default title', max_length=200, null=True),
        ),
    ]
